/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.KeyEvent; 
import java.sql.Connection; 
import java.sql.DriverManager; 
import java.sql.ResultSet; 
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; 
/**
 *
 * @author asus
 */
public class cari_karyawan extends javax.swing.JDialog {
    
DefaultTableModel model = new DefaultTableModel(); 

    /**
     * Creates new form cari_karyawan
     */
    public cari_karyawan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        util.koneksi.koneksi();
        headerTable();  
        CenterForm();
        tampilPengguna(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1_cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CARI");

        jTextField1_cari.setText("jTextField1");
        jTextField1_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1_cariKeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(652, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_cariKeyReleased
        CariPengguna();// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_cariKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     if(jTable1.getSelectedColumnCount()==1){
            int row = jTable1.getSelectedRow();
            penggajian.jTextField2_nik.setText(jTable1.getValueAt(row, 0).toString());
            penggajian.jTextField3_nama.setText(jTable1.getValueAt(row, 1).toString());
            penggajian.jTextField4_kd_jabatan.setText(jTable1.getValueAt(row, 7).toString());  
            dispose();
        }//blok mause cliked    // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cari_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cari_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cari_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cari_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cari_karyawan dialog = new cari_karyawan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1_cari;
    // End of variables declaration//GEN-END:variables

private void headerTable(){
        model =  new DefaultTableModel();
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Agama");
        model.addColumn("Tanggal Lahir");
        model.addColumn("Telpon");
        model.addColumn("Alamat");
        model.addColumn("Jabatan");     
        
        jTable1.setModel(model);
    }//ini blok header 

public void tampilPengguna(){
        model.getDataVector().removeAllElements();
        try {
            ResultSet rs=util.koneksi.st.executeQuery("select * from tbl_karyawan");
            while(rs.next()){
                Object[] data = new Object[8];
                data[0]=(rs.getString(1));
                data[1]=(rs.getString(2));
                data[2]=(rs.getString(3)); 
                data[3]=(rs.getString(4)); 
                data[4]=(rs.getString(5));
                data[5]=(rs.getString(6));
                data[6]=(rs.getString(7));
                data[7]=(rs.getString(8));                
                model.addRow(data);
             }//ini blok while       
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null,"eror tampil  : "+ e);
        } //ini blok catch
    }//blok tampil 
public void CariPengguna (){
        model.getDataVector().removeAllElements();
        try {
            ResultSet rs=util.koneksi.st.executeQuery("select * from tbl_karyawan where nama like '%"+jTextField1_cari.getText()+"%' ");
            while(rs.next()){
                Object[] data = new Object[8]; 
                data[0]=(rs.getString(1)); 
                data[1]=(rs.getString(2));
                data[2]=(rs.getString(3));
                data[3]=(rs.getString(4));  
                data[4]=(rs.getString(5));
                data[5]=(rs.getString(6));
                data[6]=(rs.getString(7));
                data[7]=(rs.getString(8));
                model.addRow(data);
             }//ini blok while       
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null,"eror tampil  : "+ e);
        } //ini blok catch 
    }//blok tampil
private void CenterForm(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
    }
}