/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.KeyEvent; 
import java.sql.Connection; 
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement; 
import java.util.ArrayList; 
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; 
/**
 *
 * @author asus
 */
public class karyawan extends javax.swing.JDialog {
DefaultTableModel model = new DefaultTableModel(); 
    /**
     * Creates new form karyawan
     */
    public karyawan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        util.koneksi.koneksi();
        headerTable(); 
        CenterForm();
        tampilPengguna();
        tombol(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1_nik = new javax.swing.JTextField();
        jTextField2_nama = new javax.swing.JTextField();
        jTextField4_tgl_lhr = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2_alamat = new javax.swing.JTextArea();
        jComboBox1_jk = new javax.swing.JComboBox<String>();
        jComboBox2_agama = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField5_kd_jabatan = new javax.swing.JTextField();
        jButton1_baru = new javax.swing.JButton();
        jButton2_simpan = new javax.swing.JButton();
        jButton3_ubah = new javax.swing.JButton();
        jButton4_hapus = new javax.swing.JButton();
        jButton5_cari = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField3_telp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("NIK");

        jLabel2.setText("Nama ");

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("Agama");

        jLabel5.setText("Tanggal Lahir");

        jLabel6.setText("Alamat");

        jLabel7.setText("Kode Jabatan");

        jTextField1_nik.setText("jTextField1_nik");

        jTextField2_nama.setText("jTextField2_nama");

        jTextField4_tgl_lhr.setText("jTextField4_tgl_lhr");

        jTextArea2_alamat.setColumns(20);
        jTextArea2_alamat.setRows(5);
        jScrollPane2.setViewportView(jTextArea2_alamat);

        jComboBox1_jk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-laki", "Perempuan" }));

        jComboBox2_agama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Islam", "Khatolik", "Protestan", "Hindu", "Budha" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField5_kd_jabatan.setEditable(false);
        jTextField5_kd_jabatan.setText("jTextField5_jabatan");
        jTextField5_kd_jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5_kd_jabatanActionPerformed(evt);
            }
        });

        jButton1_baru.setText("Baru");
        jButton1_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_baruActionPerformed(evt);
            }
        });

        jButton2_simpan.setText("Simpan");
        jButton2_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_simpanActionPerformed(evt);
            }
        });

        jButton3_ubah.setText("Ubah");
        jButton3_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_ubahActionPerformed(evt);
            }
        });

        jButton4_hapus.setText("Hapus");
        jButton4_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_hapusActionPerformed(evt);
            }
        });

        jButton5_cari.setText("jButton5");
        jButton5_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_cariActionPerformed(evt);
            }
        });

        jLabel8.setText("Telpon");

        jTextField3_telp.setText("jTextField3_telp");
        jTextField3_telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_telpActionPerformed(evt);
            }
        });

        jLabel9.setText("(tahun-bulan-tanggal)/(yyyy-mm-dd)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1_nik, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(jComboBox1_jk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2_agama, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField3_telp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField4_tgl_lhr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jButton1_baru)
                                    .addGap(29, 29, 29)
                                    .addComponent(jButton2_simpan)
                                    .addGap(26, 26, 26)
                                    .addComponent(jButton3_ubah)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton4_hapus))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField5_kd_jabatan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton5_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 38, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField4_tgl_lhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5_cari)
                            .addComponent(jTextField5_kd_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4_hapus)
                            .addComponent(jButton3_ubah)
                            .addComponent(jButton2_simpan)
                            .addComponent(jButton1_baru))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1_nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1_jk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2_agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3_telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_simpanActionPerformed
try {
            util.koneksi.st.executeUpdate( "insert into tbl_karyawan values ('"+jTextField1_nik.getText()+"','"+jTextField2_nama.getText()+"','"+jComboBox1_jk.getSelectedItem()+"','"+jComboBox2_agama.getSelectedItem()+"','"+jTextField4_tgl_lhr.getText()+"','"+jTextField3_telp.getText()+"','"+jTextArea2_alamat.getText()+"','"+jTextField5_kd_jabatan.getText()+"')"); 
            JOptionPane.showMessageDialog(null, "Berhasil menyimpan");
            tampilPengguna(); 
            tombol(true); 

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "eror Simpan : "+e);
        }//blok catch 
    }//GEN-LAST:event_jButton2_simpanActionPerformed

    private void jButton4_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_hapusActionPerformed
        try {
            util.koneksi.st.executeUpdate("delete from tbl_karyawan where nik = '"+jTextField1_nik.getText()+"' ");
            JOptionPane.showMessageDialog(null,"Berhasil menghapus ");
            tampilPengguna();
            tombol(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Eror Hapus : "+ e); 
        }//blok hapus // TODO add your handling code here:
    }//GEN-LAST:event_jButton4_hapusActionPerformed

    private void jButton3_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_ubahActionPerformed
        try {
            util.koneksi.st.executeUpdate("update tbl_karyawan set nama='"+jTextField2_nama.getText()+"',jenis_kelamin='"+jComboBox1_jk.getSelectedItem()+"',agama='"+jComboBox2_agama.getSelectedItem()+"',tanggal_lahir='"+jTextField4_tgl_lhr.getText()+"',telpon='"+jTextField3_telp.getText()+"',alamat='"+jTextArea2_alamat.getText()+"',kode_jabatan='"+jTextField5_kd_jabatan.getText()+"' WHERE nik ='"+jTextField1_nik.getText()+"'");
 
            JOptionPane.showMessageDialog(null,"Berhasil merubah ");
            tampilPengguna();
            tombol(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Eror merubah : "+ e);
        }//blok Ubah
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3_ubahActionPerformed

    private void jTextField3_telpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_telpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_telpActionPerformed

    private void jButton1_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_baruActionPerformed
        bersih();
       tombol(true);
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_baruActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if(jTable1.getSelectedColumnCount()==1){ 
            int row = jTable1.getSelectedRow();
            jTextField1_nik.setText(jTable1.getValueAt(row, 0).toString());
            jTextField2_nama.setText(jTable1.getValueAt(row, 1).toString());
            jComboBox1_jk.setSelectedItem(jTable1.getValueAt(row, 2).toString());
            jComboBox2_agama.setSelectedItem(jTable1.getValueAt(row, 3).toString());
            jTextField4_tgl_lhr.setText(jTable1.getValueAt(row, 4).toString());
            jTextField3_telp.setText(jTable1.getValueAt(row, 5).toString());
            jTextArea2_alamat.setText(jTable1.getValueAt(row, 6).toString());
            jTextField5_kd_jabatan.setText(jTable1.getValueAt(row, 7).toString());
           tombol(true);
        }//blok mause cliked // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_cariActionPerformed
   cari_jabatan objekCari = new cari_jabatan(null, rootPaneCheckingEnabled);
    objekCari.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton5_cariActionPerformed

    private void jTextField5_kd_jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5_kd_jabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5_kd_jabatanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                karyawan dialog = new karyawan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_baru;
    private javax.swing.JButton jButton2_simpan;
    private javax.swing.JButton jButton3_ubah;
    private javax.swing.JButton jButton4_hapus;
    private javax.swing.JButton jButton5_cari;
    private javax.swing.JComboBox<String> jComboBox1_jk;
    private javax.swing.JComboBox<String> jComboBox2_agama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea2_alamat;
    private javax.swing.JTextField jTextField1_nik;
    private javax.swing.JTextField jTextField2_nama;
    private javax.swing.JTextField jTextField3_telp;
    private javax.swing.JTextField jTextField4_tgl_lhr;
    public static javax.swing.JTextField jTextField5_kd_jabatan;
    // End of variables declaration//GEN-END:variables
void bersih(){ 
        jTextField1_nik.setText(""); 
        jTextField2_nama.setText("");
        jTextField3_telp.setText("");
        jTextField4_tgl_lhr.setText("");
        jTextArea2_alamat.setText("");
        jTextField5_kd_jabatan.setText("");
    }//ini blok bersih

void tombol(boolean status){
         jButton1_baru.setEnabled(true);
         jButton2_simpan.setEnabled(status);
         jButton3_ubah.setEnabled(status);
         jButton4_hapus.setEnabled(status);         
     }//blok tombol 

private void headerTable(){
        model =  new DefaultTableModel();
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Agama");
        model.addColumn("Tanggal Lahir");
        model.addColumn("Telpon");
        model.addColumn("Alamat");
        model.addColumn("Kode Jabatan");
        
        jTable1.setModel(model);
    }//ini blok header 
public void tampilPengguna(){
        model.getDataVector().removeAllElements();
        try {
            ResultSet rs=util.koneksi.st.executeQuery("select * from tbl_karyawan");
            while(rs.next()){
                Object[] data = new Object[8];
                data[0]=(rs.getString(1));
                data[1]=(rs.getString(2));
                data[2]=(rs.getString(3));
                data[3]=(rs.getString(4));
                data[4]=(rs.getString(5));
                data[5]=(rs.getString(6));
                data[6]=(rs.getString(7));
                data[7]=(rs.getString(8));
                model.addRow(data);
             }//ini blok while       
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null,"eror tampil  : "+ e);
        } //ini blok catch
        bersih(); 
    }//blok tamp
private void CenterForm(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
    }

}
