/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.KeyEvent; 
import java.sql.Connection; 
import java.sql.DriverManager;
import java.sql.ResultSet; 
import java.sql.Statement; 
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.koneksi; 
import laporan.mainlaporan;
/**
 *
 * @author asus
 */
public class penggajian extends javax.swing.JDialog {
DefaultTableModel model = new DefaultTableModel(); 
    /**
     * Creates new form penggajian
     */
    public penggajian(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        koneksi.koneksi();
        headerTable();
        tampilData ();
        bersih();
        CenterForm();
        tombol(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_no = new javax.swing.JTextField();
        jTextField2_nik = new javax.swing.JTextField();
        jTextField3_nama = new javax.swing.JTextField();
        jTextField4_kd_jabatan = new javax.swing.JTextField();
        jButton1_baru = new javax.swing.JButton();
        jButton2_simpan = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4_hapus = new javax.swing.JButton();
        jTextField5_Keterangan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField6_tanggal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("NO");

        jLabel3.setText("NIK");

        jLabel4.setText("Nama");

        jLabel5.setText("Kode Jabatan");

        jLabel6.setText("Keterangan");

        jTextField1_no.setText("jTextField1");

        jTextField2_nik.setEditable(false);
        jTextField2_nik.setText("jTextField2");
        jTextField2_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_nikActionPerformed(evt);
            }
        });

        jTextField3_nama.setEditable(false);
        jTextField3_nama.setText("jTextField3");

        jTextField4_kd_jabatan.setEditable(false);
        jTextField4_kd_jabatan.setText("jTextField4");

        jButton1_baru.setText("BARU");
        jButton1_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_baruActionPerformed(evt);
            }
        });

        jButton2_simpan.setText("SIMPAN");
        jButton2_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_simpanActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4_hapus.setText("HAPUS");
        jButton4_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_hapusActionPerformed(evt);
            }
        });

        jTextField5_Keterangan.setText("jTextField8");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Tanggal");

        jTextField6_tanggal.setText("jTextField6");
        jTextField6_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6_tanggalActionPerformed(evt);
            }
        });

        jLabel7.setText("(yyyy-mm-dd)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addGap(57, 57, 57)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1_baru)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2_simpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4_hapus))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1_no, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField5_Keterangan)
                                    .addComponent(jTextField4_kd_jabatan)
                                    .addComponent(jTextField3_nama)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField2_nik, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField6_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)))))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField6_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2_nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4_kd_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5_Keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4_hapus)
                    .addComponent(jButton2_simpan)
                    .addComponent(jButton1_baru))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     cari_karyawan objekCari = new cari_karyawan(null, rootPaneCheckingEnabled);
     objekCari.setVisible(true); 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
 if(jTable1.getSelectedColumnCount()==1){
            int row = jTable1.getSelectedRow();
            jTextField1_no.setText(jTable1.getValueAt(row, 0).toString());
            jTextField6_tanggal.setText(jTable1.getValueAt(row, 1).toString());
            jTextField2_nik.setText(jTable1.getValueAt(row, 2).toString());
            jTextField3_nama.setText(jTable1.getValueAt(row, 3).toString());
            jTextField4_kd_jabatan.setText(jTable1.getValueAt(row, 4).toString());
            jTextField5_Keterangan.setText(jTable1.getValueAt(row, 8).toString()); 
           
            tombol(true);
        }//blok mause cliked     
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField2_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_nikActionPerformed

    private void jTextField6_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6_tanggalActionPerformed

    private void jButton2_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_simpanActionPerformed
       try {util.koneksi.st.executeUpdate("insert into tbl_penggajian values ('"+jTextField1_no.getText()+"','"+jTextField6_tanggal.getText()+"','"+jTextField2_nik.getText()+"','"+jTextField4_kd_jabatan.getText()+"','"+jTextField5_Keterangan.getText()+"')");
       
            JOptionPane.showMessageDialog(null, "Berhasil menyimpan");
            tampilData();
            cetakNota();
            tombol(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "eror Simpan : "+e); 
        }//blok catch  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2_simpanActionPerformed

    private void jButton4_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_hapusActionPerformed
       try {
 util.koneksi.st.executeUpdate("delete from tbl_penggajian where no_penggajian ='"+jTextField1_no.getText()+"' "); 
             JOptionPane.showMessageDialog(null, "Berhasil menghapus");
             tampilData();
             tombol(true); 
        } catch (Exception e) { 
             JOptionPane.showMessageDialog(null, "eror hapus : "+e);
        }//blok catch
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton4_hapusActionPerformed

    private void jButton1_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_baruActionPerformed
      tombol(true); 
      bersih();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1_baruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penggajian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penggajian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penggajian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penggajian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                penggajian dialog = new penggajian(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_baru;
    private javax.swing.JButton jButton2_simpan;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton4_hapus;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1_no;
    public static javax.swing.JTextField jTextField2_nik;
    public static javax.swing.JTextField jTextField3_nama;
    public static javax.swing.JTextField jTextField4_kd_jabatan;
    private javax.swing.JTextField jTextField5_Keterangan;
    private javax.swing.JTextField jTextField6_tanggal;
    // End of variables declaration//GEN-END:variables
void bersih(){ 
        jTextField1_no.setText("");
        jTextField2_nik.setText("");      
        jTextField3_nama.setText("");      
        jTextField4_kd_jabatan.setText("");
        jTextField5_Keterangan.setText("");
        jTextField6_tanggal.setText("");
        
    }
    private void headerTable(){
        model =  new DefaultTableModel();
        model.addColumn("NO");
        model.addColumn("Tanggal");
        model.addColumn("NIK");
        model.addColumn("Nama"); 
        model.addColumn("Kode Jabatan"); 
        model.addColumn("Jabatan");
        model.addColumn("Gaji");
        model.addColumn("Keterangan"); 
        
        
        jTable1.setModel(model);
    }//ini tag header
    public void tampilData (){
        model.getDataVector().removeAllElements();
        try {
            ResultSet rs=util.koneksi.st.executeQuery("SELECT * from view_penggajian");
            while(rs.next()){
                Object[] data = new Object[8];
                data[0]=(rs.getString(1));
                data[1]=(rs.getString(2));
                data[2]=(rs.getString(3));
                data[3]=(rs.getString(4));
                data[4]=(rs.getString(5));
                data[5]=(rs.getString(6));
                data[6]=(rs.getString(7));
                data[7]=(rs.getString(8));
                
                model.addRow(data);
             }//ini tag while       
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null,"eror tampil  : "+ e);
        } //ini tag catch
        bersih();
    }
     void tombol(boolean status){
         jButton1_baru.setEnabled(true);
         jButton2_simpan.setEnabled(status);
         jButton4_hapus.setEnabled(status);
         
     }//blok tombol
     private void CenterForm(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
    }
     void cetakNota(){
         mainlaporan laporan = new mainlaporan();
        laporan.ParameterLaporan="parameter1_no";
        laporan.idLaporan=AmbilIdNota();
        laporan.namaLaporan="report5_transaksi";
        laporan.cetakLaporanMaster();        
     }//cetak nota 
      

     public String AmbilIdNota(){
        String id="0";
         try {
            ResultSet rs=util.koneksi.st.executeQuery("SELECT * FROM view_penggajian ORDER BY no_penggajian DESC LIMIT 1");
            if(rs.next()){
                id=rs.getString(1);
            }//ini tag while       
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null,"eror tampil  : "+ e);
        } //ini tag catch 
        return id; 
    }
}
